# ä¸»é¢˜
theme:
    switch: true
    default: style-light

# å›¾æ ‡
favicon:
    logo: /img/logo-black.png
    hidden: /img/tako.png?v=1
    icon16: /img/tako.png?v=1
    icon32: /img/tako.png?v=1

# ç”¨æˆ·ä¿¡æ¯
user:
    name: Tako Senpai
    first_name: Tako
    last_name:
    email: takosenpai2687@gmail.com
    domain: https://tako-tako.netlify.app
    avatar: /img/avatar.jfif
    describe: Tako Senpai lives here.

# å¯¼èˆªæ 
top_bars:
    - title: ä¸»é¡µ
      url: /
    - title: åˆ†ç±»
      url: /categories/
      noswup: true
    - title: æ ‡ç­¾
      url: /tags/
      noswup: true
    - title: å½’æ¡£
      url: /archives/
      noswup: true
    - title: å‹é“¾
      url: /links/
      noswup: true

# ä¾§è¾¹æ 
sidebar:
    social: # ç¤¾äº¤åœ°å€
        - name: github
          icon: fab fa-github
          url: https://github.com/takosenpai2687
        - name: takotako
          icon: ğŸ™

    # æ‰“å­—åŠ¨ç”»
    typedTextPrefix: Student
    typedText: ["&& Web Developer"]

    # ä¸ªäººä¿¡æ¯
    info:
        - key: ğŸ“
          val: Sydney
        - key: ğŸ‚
          val: June 3
        - key: ğŸŒ
          val: ä¸­æ–‡, English
        - key: ğŸ«(UG)
          val: UNSW
        - key: ğŸ«(PG)
          val: USyd

# æ¨ªå¹…
banner:
    index:
        type: img
        bgurl: /img/guyun.jpg
        bannerTitle: El Psy <br> Congroo
        bannerText:
        fit: cover
    archive:
        type: img
        bgurl: /img/guyun.jpg
        bannerTitle: El Psy <br> Congroo
        bannerText:
        fit: cover
    links:
        type: img
        bgurl: /img/guyun.jpg
        bannerTitle: El Psy <br> Congroo
        bannerText:
        fit: cover
    default:
        type: img
        bgurl: /img/guyun.jpg
        bannerTitle: El Psy <br> Congroo
        bannerText: <body>
        fit: cover

# é¡µè„š
footer:
    powered:
        enable: true

# å¸ƒå±€
layout:
    path: layout

# æ–‡ç« ç›®å½•
toc:
    enable: true
    list_number: true
    max_depth: 3
    min_depth: 1

# ç‰ˆæƒä¿¡æ¯
creative_commons:
    license: by-nc-sa
    language: deed.zh
    post: true
    clipboard: true

# åˆ†ç±»å¡ç‰‡
categorie_card:
    enable: true
    len: 3
    list: ["Frontend", "Backend", "Algorithms"]

# å›ºå®šæŒ‰é’®å—
rightside:
    readmode: true
    aside: true

# æ—¥æœŸæ ¼å¼åŒ–
datetime_foramt:
    post_card:
        date: YYYY/MM/DD
        time: HH:mm
    post_info:
        date: YYYY/MM/DD
        time: HH:mm
    archive:
        date: YYYY/MM/DD
        time: HH:mm

# ä»£ç å—
highlight:
    theme: true
    title: default
    copy: true
    lang: true
    code_word_wrap: fasle
    height_limit: 200 # è¶…å‡ºæ—¶ï¼Œæ˜¾ç¤ºæŠ˜å æŒ‰é’®

# å‹é“¾
links:
  - name: Tako Tako
    url: https://tako-tako.netlify.app/
    image: https://tako-tako.netlify.app/img/tako.png
    desc: Tako Senpai è‡ªç ”è‡ªç”¨çš„æ¸¸æˆå°å·¥å…·
